version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - run: curl -L https://unpkg.com/@pnpm/self-installer | sudo node

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pnpm-lock.yaml" }}
            - v1-dependencies-

      - run: pnpm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "pnpm-lock.yaml" }}

      - run: pnpm run test
      - run: pnpm run build

      - persist_to_workspace:
          root: .
          paths:
            - dist/
            - oBindings.toc

  publish:
    docker:
      - image: cibuilds/github:0.10

    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            sed -i.bak -E "s/^(## Version: )(.*)$/\1$CIRCLE_TAG/" ./artifacts/${CIRCLE_PROJECT_REPONAME}.toc && rm ./artifacts/${CIRCLE_PROJECT_REPONAME}.toc.bak
            mv artifacts ${CIRCLE_PROJECT_REPONAME}
            zip -r ${CIRCLE_PROJECT_REPONAME}.zip ${CIRCLE_PROJECT_REPONAME}/
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ${CIRCLE_PROJECT_REPONAME}.zip

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
